name: tsp-cuda113
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - torchvision=0.12.0
  - pytorch=1.11.0
  - cudatoolkit=11.3.1
  - pandas
  - h5py
  - av
  - joblib
  - tqdm
  - ffmpeg-python=0.2.0
